name: "Build and Deploy"

on:
  push:
    branches:
      - master

jobs:
    build:
      name: Build and Deploy
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install hugo
        run: sudo snap install hugo

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: make install

      - name: Build
        run: make build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
